# Generated by Django 2.0.1 on 2018-03-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35)),
                ('ip', models.CharField(max_length=64)),
                ('payout', models.DecimalField(decimal_places=8, max_digits=12)),
                ('prev_balance', models.DecimalField(decimal_places=8, max_digits=12)),
                ('tx_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35)),
                ('ip', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
